### ISSUE TITLE
Feature Request: /Format CSV

### ISSUE THREAD

**Issue by alazare619** [cunninghamp/Collect-ServerInfo#1]
Option to format to a CSV or a XLS since they do exist to begin with instead of always /html. Would be usefull as I Could easly then add (paste) this to my Onenote documentation without having to call a html file from inside of it.

**Comment by cunninghamp** [comment]
@alazare619 I've thought about this before. Tricky part seems to be handling servers with different numbers of things, such as memory banks, or disks/volumes. E.g. how to construct a CSV when Server1 might have C: and D: volumes, and Server2 might have C:, E:, F:, and G: volumes. Any thoughts on what you'd be happy to have excluded or collapsed into a single cell to keep the CSV structure manageable?

**Comment by alazare619** [comment]
I was thinking a seperate CSV for each server something along the lines of
foreach servers in servers export /format:CSV  in psuedo code

**Comment by cunninghamp** [comment]
@alazare619 can you manually create a CSV that looks how you think it would look? To me it seems problematic because there's multiple tables in the HTML report of different sizes, so combining them all into a single CSV... going to be tough.

**Comment by alazare619** [comment]
https://gist.githubusercontent.com/alazare619/bb32b0c5b09ac2901f85/raw/1ae684b3d55e89a042acce545aa7da788f6b04c7/gistfile1.txt

save that as a CSV and you got the template you would just need to have your variables pushed to it.

**Comment by alazare619** [comment]
that is if you are storing your variables in memory atleast

**Comment by cunninghamp** [comment]
To me CSV format would mean one header row, and one line per server, and a structured format that is able to be ingested or imported elsewhere. What you're showing me is one CSV per server, with multiple header rows and and an unstructured format that would not be easily imported into anything else.
